import type { Metadata } from "next";
import Navbar from "./Components/Navbar";
import { Sora, DM_Sans } from "next/font/google";
import "./globals.css";

const DMSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <Navbar />
      </header>
      <body
        className={`${DMSans.variable} ${sora.variable} antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
